name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/*'
      - 'test/*'
  pull_request:
    branches:
      - main
      - 'release/*'

env:
  SRC_PATH: './src/'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: dotnet build
        if: success()
        run: dotnet build
        working-directory: ${{ env.SRC_PATH }}

      - name: dotnet test
        if: success()
        run: dotnet test --no-build --verbosity normal
        working-directory: ${{ env.SRC_PATH }}

