name: Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    name: Git Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        if: success()
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          RELEASE_BRANCHES: main
          INITIAL_VERSION: 'v6.0.0'
          DEFAULT_BUMP: minor
          WITH_V: true
          VERBOSE: true
